
    <title>Disclaimer and Terms</title>
    <style>
        /*body {*/
        /*    font-family: Arial, sans-serif;*/
        /*    line-height: 1.6;*/
        /*    margin: 0;*/
        /*    padding: 0;*/
        /*    background-color: #f4f4f4;*/
        /*}*/
        /*.container {*/
        /*    width: 80%;*/
        /*    margin: auto;*/
        /*    overflow: hidden;*/
        /*    background: #fff;*/
        /*    padding: 20px;*/
        /*    box-shadow: 0 0 10px rgba(0,0,0,0.1);*/
        /*}*/
        h1, h2 {
            color: #333;
        }
        ul {
            list-style: disc;
            padding-left: 20px;
        }
    </style>
 <br>
    <div class="container" style="margin-top: 15vh;">
        <h1>Disclaimer/Advice</h1>
        <li style="list-style-type: disc;" >Visitors are advised to make appropriate thorough enquiries before acting upon any profile/biodata. This website does not vouch or subscribe to the claims and representations made by advertisers regarding particulars of the bride/groom.</li>
 <br>
        <h1>Terms</h1>
        <li style="list-style-type: disc;" >This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
        <li style="list-style-type: disc;" >This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and the terms and conditions for access or usage of www.shubhweds.com (the "Website").</li>
        <li style="list-style-type: disc;" >PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE WEBSITE. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS ("Agreement"). If you do not want to be bound by the Terms and Conditions, you must not use the Website or the Shubhweds Services. The Terms and Conditions also includes the applicable policies which are incorporated herein by way of reference and as amended from time to time (the "Terms and conditions").</li>
         <br>
        <h2>In these Terms:</h2>
        <ul>
            <li>References to "Shubhweds member" shall mean the end user accessing the Website/services, its contents or using the Shubhweds Services offered. Shubhweds member also includes persons such as father, mother, brother, sister, relative or a friend ("Registrant") of the prospective bride/ bridegroom.</li>
            <li>The terms "You" and "User" shall be interchangeably used for "Shubhweds member".</li>
            <li>"Shubhweds Services" means a collective reference to the Shubhweds service provided by Shubhweds.com.</li>
        </ul>
 <br>
        <h2>Eligibility:</h2>
        <ul>
            <li>A) Membership and rights of admission is reserved solely for:
                <ul>
                    <li>I. Indian Nationals & Citizens.</li>
                    <li>II. Persons of Indian Origin (PIO).</li>
                    <li>III. Non Resident Indians (NRI).</li>
                    <li>IV. Persons of Indian Descent or Indian Heritage.</li>
                    <li>V. Persons who intend to marry persons of Indian Origin.</li>
                </ul>
            </li>
            <li>B) Further in capacity as Shubhweds member you confirm that you are:
                <ul>
                    <li>I. 18 years or above (if you are a woman) or 21 years or above (if you are a man);</li>
                    <li>II. If you are a resident of any other Country, you are legally competent to marry as per the local rules applicable to your country and you shall comply with the Indian laws for marrying a person of Indian Origin.</li>
                </ul>
            </li>
            <li>C) In case you are a Registrant of the prospective bride/ bridegroom and has created profile in Shubhweds Website/App on behalf of them or is accessing the Shubhweds Website/App on behalf of them implies that you have taken their consent for their profile creation in Shubhweds and for accessing the Shubhweds Website/App.</li>
        </ul>
 <br>
        <h2>Registration</h2>
        <ul>
            <li>A. We expect that you would complete the online registration process with fairness and honesty in furnishing true, accurate, current, complete information and with providing recent photos of you which will help you to meet your parameters.</li>
            <li>B. By joining/visiting shubhweds.com you hereby confirm that you do not have any objection to receiving emails, messages/sms and calls from shubhweds.com and members of shubhweds.com as long as you are a registered member of shubhweds.com.</li>
            <li>C. If at any point of time Shubhweds comes to know or is so informed by third party or has reasons to believe that any information provided by you for registration (including photos) or otherwise is found to be untrue, inaccurate, or incomplete, Shubhweds shall have full right to suspend or terminate (without any notice) your Shubhweds membership and forfeit any amount paid by you towards Shubhweds membership fee and refuse to provide Shubhweds service to you thereafter.</li>
            <li>D. Shubhweds also reserves the right to block the registration of your profile on Website/App, if any, in the case of your contact details/links being entered in irrelevant fields or if there are errors in any data entered by the Shubhweds members in their profile.</li>
            <li>E. Registration of duplicate profiles of the same person is not allowed in Shubhweds Website/App. Shubhweds shall have full right to suspend or terminate (without any notice) such duplicate profile.</li>
            <li>F. You acknowledge and confirm that your registration with Shubhweds and the usage of Shubhweds services is with the bonafide intention of marriage and not otherwise. Shubhweds Membership is restricted strictly to the registered Shubhweds individual member only.</li>
        </ul>
 <br>
        <h2>Account Security</h2>
        <ul>
            <li>You are responsible for safeguarding the confidentiality of your Shubhweds login credentials such as your user id, password, OTP, etc., and for restricting access to your computer/mobile to prevent unauthorized access to your account. You agree to accept responsibility for all activities that occur under your account.</li>
        </ul>
 <br>
        <h2>Role and Responsibility of Shubhweds</h2>
        <ul>
            <li>A. Shubhweds's obligation is only to provide an interface to its registered members to search their prospect themselves without any assistance.</li>
            <li>B. The profile search conducted by any Shubhweds member and the matches shown thereof are automatically generated by Shubhweds, and based on the partner preference set by you. In the event of Shubhweds member changing their partner preference on the Website/App, then the automated system generated prospect results of the Website/App may also undergo corresponding change.</li>
            <li>C. Shubhweds does not prohibit any Shubhweds member from sending interest to your profile or communicating to you based on their partner preference. But you are at the liberty to deny their interest or proceed further if you are interested.</li>
            <li>D. Shubhweds cannot guarantee or assume responsibility for any specific results from the use of the data available from the Shubhweds service.</li>
            <li>E. Shubhweds shall safeguard sensitive user information using security standards, authentication mechanisms, access controls and encryption techniques.</li>
            <li>F. Shubhweds cannot guarantee the complete protection of user data while it is in transit, or prevent any tampering of the data by a third party with malicious intent before the data reaches the Shubhweds servers.</li>
            <li>G. Shubhweds do not authenticate/endorse any information of any profile and hence you as a user need to verify the credentials and information provided by other users.</li>
        </ul>
 <br>
        <h2>Role and Responsibility of Shubhweds Member</h2>
        <ul>
            <li>A. You, shall safeguard your profile information by creating a strong password during profile creation with combination of alphabets, both upper and lower case and numbers.</li>
            <li>B. Any information / data required by Shubhweds for using the Shubhweds services shall be provided by the Shubhweds Member, as and when so sought by Shubhweds.</li>
            <li>C. You are requested to verify the credentials of the prospect, exercise due care and caution regarding their profile information which includes marital status, educational qualifications, financial status, occupation, character, health status, etc. and satisfy yourself before making a choice of your match. Shubhweds shall not be liable for shortcoming due to any misrepresentations made by any of its Shubhweds members.</li>
            <li>D. To get better search results, Shubhweds Members are expected to provide latest photograph which should not be more than 3 (three) months old. Providing old photographs/ photographs of others, inaccurate / false information shall be treated as violation of terms and conditions and Shubhweds shall retain their right under clause 2 (b) of this terms and conditions.</li>
            <li>E. Shubhweds Members are advised to refrain from:
                <ul>
                    <li>i. Entering into any financial transactions with prospects. Shubhweds Members shall not seek financial help or provide financial help from / to the other Shubhweds Members.</li>
                    <li>ii. Using abusive language when they communicate with the other Shubhweds Members.</li>
                    <li>iii. Being discriminative or using racial comments etc.</li>
                    <li>iv. Sharing of confidential and personal data with each other but not limited to sharing of bank details, etc.</li>
                    <li>v. Entering into physical relationship with any prospect before marriage.</li>
                    <li>vi. Violating any law for the time being in force.</li>
                    <li>vii. From mentioning details of other matrimonial services while sending personalized messages.</li>
                </ul>
            </li>
            <li>F. Shubhweds Members are expected to be cautious of prospects who ask for favours, money etc or call from multiple phone numbers, only interact over phone, doesn't come forward for face to face meeting (physically or through video calls) and don’t involve family and friends in matchmaking. Beware of suspended profiles status before you finalize an alliance with the prospect.</li>
            <li>G. The Shubhweds members agrees that for getting effective search results of prospects on Website/App you will regularly log in to the profile maintained in the Website/App and send expression of interest which is an automated message to prospects as a free Shubhweds member, and in the event you have availed paid Shubhweds package, you can send personalized messages to prospects to show your expression of interest/replies. Shubhweds member also may review the expression of interest sent to you / read the messages sent to you by prospects and may respond suitably.</li>
            <li>H. You also agree that while accessing / using the Website/App, you will be guided by the terms and conditions of the Website/App including but not limited to the use of feature of website /App like chat instantly with prospect, viewing horoscope of prospects, enhancing privacy settings (photo/horoscope/phone number) or for viewing social and professional profile of members on their Facebook, LinkedIn, etc.</li>
            <li>I. If the Shubhweds Member fails to update in Shubhweds website/App, any change in the particulars furnished in their profile/ then the Shubhweds membership may be suspended by Shubhweds at its sole discretion.</li>
            <li>J. Shubhweds member shall, in case of finalization of his/her/their Registrant’s marriage, delete their profile by themselves or intimate Shubhweds for removal/deletion of their profile.</li>
            <li>K. Shubhweds Members agree to use secure devices, software and networks in a private place for accessing the Shubhweds services.</li>
            <li>L. Shubhweds Members shall not probe, scan or test the vulnerabilities of the Shubhweds Website/App or any network connected to the Website/App nor breach the security measures instituted by Shubhweds.</li>
            <li>M. You shall also not make any payment / transfer any amount to the account of any employees. All payments shall be made only to Shubhweds account.</li>
            <li>N. Shubhweds members are expected to raise queries to resolve their complaints and grievances and shall not air their grievance/complaints in social media.</li>
        </ul>
 <br>
        <li>Shubhweds by its automatic system sends to its member(s) profile(s) of the prospect by way of images/documents/messages/links. Shubhweds member confirms that the mobile number submitted to it for verification or alternative number if any provided, is not registered with the Do Not Disturb / National Customer Preference Register and they shall not initiate any complaint. Shubhweds Member further confirms that even if Shubhweds Member is registered with the telecom service provider under the category Do Not Disturb / National Customer Preference Register the calls from Shubhweds either to the verified mobile number or alternative number if any provided shall not be treated as promotional calls.</li>
     <br>
     <h2>Confidentiality</h2>
        <li>Any feedback you provide to Shubhweds shall be deemed to be non-confidential. Shubhweds shall be free to use such feedback/information on an unrestricted basis. Further, by submitting the feedback, you represent and warrant that (i) your feedback does not contain confidential or proprietary information of yourself or third parties; (ii) Shubhweds member is not under any obligation of confidentiality, express or implied, with respect to the feedback; (iii) you are not entitled to any compensation or reimbursement of any kind from Shubhweds for the feedback under any circumstances.</li>
 <br>
        <h2>Privacy of Membership</h2>
        <li>To protect your privacy and understand our practices as amended from time to time, please read and follow our <a href="#privacy-policy">Privacy Policy</a>, which also governs your visit to Shubhweds. The personal information/data provided to us by you during the course of usage of Shubhweds will be treated as confidential and in accordance with the Privacy Policy and applicable laws and regulations.</li>
 <br>
        <h2>Disputes between Members</h2>
        <ul>
            <li style="list-style-type: disc;" >Shubhweds Members are solely responsible for the communications (through any medium) with prospect or vice versa. Shubhweds expressly disclaims any responsibility or liability for any monetary transaction(s) or exchange(s) or interaction(s) or passing of information(s) etc. between any Shubhweds members inter se via e-mail, chat, interaction, WhatsApp or any other medium of communication between Shubhweds members either using website/App or otherwise.</li>
            <li style="list-style-type: disc;" >Shubhweds has no obligation to monitor any such disputes arising between the Shubhweds members, and Shubhweds shall not be party to any such dispute/litigation etc.</li>
            <li style="list-style-type: disc;" >Shubhweds is not a broker or the agent of any Shubhweds member, and Shubhweds does not partake in the exchange of any kind of discussion between the Shubhweds members and prospects or the results of their discussion.</li>
        </ul>
 <br>
        <h2>Content Right</h2>
        <ul>
            <li>You agree that all content of Shubhweds belongs to Shubhweds including advertisements on the Website/App for which Shubhweds has the requisite license/right in terms hereof to display the same on our Website/App.</li>
            <li>You acknowledge that you alone are responsible and liable for the content (mandatory or optional content you provided on our website) and information including the profile details, photograph, and other content(s) keyed in the relevant field of the Website/App at the time of the creation of the Shubhweds profile or subsequently modified by you and also for all the post and communication (including personalized messages sent by Shubhweds paid members) with other member(s). You hereby represent and warrant that you own all rights, title and interest in your content/information or have the necessary licenses, rights, consents, and permissions to provide the said content/information. However, by submitting the content/information to Shubhweds, you hereby grant Shubhweds a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, prepare derivative works of, display, publish, communicate to the public, law enforcement agencies, courts, and Shubhweds's business and services, including without limitation for promoting, communicating to the public and redistributing part or all of the content/information (and derivative works thereof) in any media formats and through any media channels.</li>
            <li>While Shubhweds does not accept any obligation to monitor the content/information in your profile, if the content/information is found not to be in compliance with these Terms and conditions, Shubhweds may delete the content/information and/or terminate or suspend your registration or (without a refund of any subscription paid by you in terms of clause 2 (b) of these terms and conditions). You agree that if the situation warrants Shubhweds may at its sole discretion put restrictions on any Shubhweds member to other member's communications.</li>
        </ul>
 <br>
        <h2>Limitation of Liability</h2>
        <ul>
            <li style="list-style-type: disc;" >Shubhweds shall under no circumstances be liable or responsible to the Shubhweds member or his/her authorized Representative or Registrant or any third party for any direct, indirect, special, exemplary, incidental, or consequential damages of any character including, without limitation, damages resulting from the use of our Website/App.</li>
            <li style="list-style-type: disc;" >Shubhweds informs you that the exchange of profile(s) through or by Shubhweds should not in any way be construed as a matrimonial offer and/or recommendation and/or advice or guarantee given to the Shubhweds member, from/or by Shubhweds.</li>
            <li style="list-style-type: disc;" >Notwithstanding anything to the contrary contained herein, Shubhweds's liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to Shubhweds, for any specific Shubhweds paid package, and no further.</li>
            <li style="list-style-type: disc;" >Shubhweds will not be liable in case of any wrong/improper match made due to unavailability of profiles from Shubhweds website/App.</li>
            <li style="list-style-type: disc;" >Shubhweds shall under no circumstances be liable for any Shubhweds member entering into a financial transaction with any other Shubhweds Member.</li>
            <li style="list-style-type: disc;" >Shubhweds shall under no circumstances be liable for any Shubhweds members not responding/reciprocating when you approach them for matrimonial alliance.</li>
        </ul>
 <br>
        <h2>Class Action Suits</h2>
        <li>You acknowledge and confirm that you will not bring or participate in any class action or other class proceeding in connection with any dispute with Shubhweds. Further, neither you nor Shubhweds agrees to class arbitration.</li>

        <h2>General</h2>
        <ul>
            <li style="list-style-type: disc;" >In the event you file a false complaint against another prospect on our Website/App and consequently we have suspended/deleted that prospect’s profile based on your complaint, then we reserve our right to initiate appropriate legal (Civil/Criminal) action against you and claim any and all costs expenses from you, for such irresponsible/misrepresentation/illegal/unlawful action. We also reserve our right to suspend your profile and forfeit any and all amounts paid by you for the Shubhweds services as per clause 2 (b) of these terms and conditions.</li>
            <li style="list-style-type: disc;" >Notwithstanding anything contained herein, Shubhweds reserves the absolute right to delete, in any manner as it deems fit, any content of any profile listing placed on website/App (once such instance comes to Shubhweds notice) in order to ensure that proper consent has been obtained by you, prima facie accuracy and the prevailing laws in force for the time being, especially those relating to providing any obscene, libelous, blasphemous, slanderous, defamatory or invasive of another person’s (deceased or alive) right of privacy or publicity, or that may reasonably be deemed to be harmful, vulgar, pornographic, abusive, harassing, threatening, hateful, objectionable with respect to race, religion, creed, nationality, gender or otherwise unfit for reproduction; or suggests or encourages unfair or illegal/indecent, unlawful activity. Shubhweds also reserves the right to block/delete/suspend the profile which might be offensive, illegal or that might violate the rights, harm or threaten the safety of our office bearers/employees (including undue communication with any employee) and/or other registered prospects or using our Shubhweds website/App as a means of communication while sending messages to other Shubhweds members regarding their profile identity in other matrimonial websites.</li>
            <li style="list-style-type: disc;" >Once your paid membership expires, you cannot avail the unexpired balance phone number count/unexpired messages. Similarly, you will not be able to avail any renewal offer or refund for any unused benefits. Any extension or renewal of membership would be subject to the terms and conditions prevailing at the time of such extension/renewal.</li>
        </ul>
 <br>
        <h2>Disclaimer</h2>
        <ul>
            <li style="list-style-type: disc;" >Shubhweds’s services are provided on an "as is" basis and without warranties of any kind, either express or implied.</li>
            <li style="list-style-type: disc;" >Shubhweds does not warrant that its services will be uninterrupted, error-free, secure, or free from viruses or other harmful components.</li>
            <li style="list-style-type: disc;" >Shubhweds does not guarantee the accuracy, completeness, or reliability of any information or content on the Website/App.</li>
            <li style="list-style-type: disc;" >Shubhweds is not responsible for any damages, loss, or harm resulting from your use of its services.</li>
        </ul>
 <br>
        <h2>Indemnity</h2>
        <li>You agree to indemnify and hold Shubhweds and its affiliates, officers, directors, employees, and agents harmless from any claims, liabilities, damages, losses, or expenses arising out of or in connection with your use of the services, content, or violation of these Terms.</li>
 <br>
        <h2>Termination</h2>
        <ul>
            <li style="list-style-type: disc;" >Shubhweds reserves the right to terminate or suspend your membership at its sole discretion for any violations of the terms and conditions.</li>
            <li style="list-style-type: disc;" >You may terminate your membership by providing a 7-day written notice to Shubhweds.</li>
        </ul>
 <br>
        <h2>Mode of Payment</h2>
        <li>Payments for Shubhweds services are processed as per the guidelines of the Reserve Bank of India (RBI). Services will be activated upon realization of payment.</li>
 <br>
        <h2>Refund/Cancellation and Assignment</h2>
        <ul>
            <li  style="list-style-type: disc;" >Payments made are non-refundable.</li>
            <li  style="list-style-type: disc;" >Memberships are non-transferable and cannot be assigned to other individuals.</li>
        </ul>
 <br>
        <h2>Renewal</h2>
        <li>Memberships are renewed annually. If you do not wish to renew, you must cancel your membership before the renewal date.</li>
 <br>
        <h2>Jurisdiction</h2>
        <li><strong>Disputes arising under these Terms shall be governed by the laws of India and subject to the jurisdiction of the courts in Nashik City, Maharashtra.</strong></li>
 <br>
        <h2>Customer Care / Customer Service</h2>
        <li >For any queries or assistance, you can contact our customer service at:</li>
        
        <ul>
            <li style="list-style-type: disc;" >Email: <a href="mailto:support@shubhweds.com">support@shubhweds.com</a></li>
            <li style="list-style-type: disc;" >Phone: +91 7014378070</li>
        </ul>
        <br>
        <hr>

        <h1>Privacy Policy</h1>

        <h2 style="font-size:25px">Introduction</h2>
        <li>Welcome to [Shubhweds] ("we," "our," "us"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website [www.shubhweds.com], including any other media form, media channel, mobile website, or mobile application related or connected thereto (collectively, the "Site"). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.</li>
 <br>
        <h2 style="font-size:25px">Information We Collect</h2>
        
            <li>We may collect information about you in a variety of ways. The information we may collect on the Site includes:</li>
             <ul>
            <li style=" list-style-type: disc"><strong>Personal Data: </strong>
Personally identifiable information, such as your name, shipping address, email address, and telephone number, and demographic information, such as your age, gender, hometown, and interests, that you voluntarily give to us when you register with the Site or when you choose to participate in various activities related to the Site, such as online chat and message boards.
</li>
            <li style=" list-style-type: disc"><strong>Derivative Data:</strong>
Information our servers automatically collect when you access the Site, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and after accessing the Site.
</li>
            <li style=" list-style-type: disc"><strong>Financial Data: </strong>Financial information, such as data related to your payment method (e.g., valid credit card number, card brand, expiration date) that we may collect when you purchase, order, return, exchange, or request information about our services from the Site.</li>
            <li style=" list-style-type: disc"><strong>Networks: </strong>Data From Social 
User information from social networking sites, such as [social media sites, e.g., Facebook, Google+, Twitter], including your name, your social network username, location, gender, birth date, email address, profile picture, and public data for contacts, if you connect your account to such social networks.
</li>
            
        </ul>
         <br>
        <h2 style="font-size:25px">Use of Your Information

</h2>
        <li>
Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Site to:
</li>
<ul>
    <li style="list-style-type: disc;">Create and manage your account.</li>
    <li style="list-style-type: disc;">Process your transactions and send you related information, including purchase confirmations and invoices.</li>
    <li style="list-style-type: disc;">Communicate with you about products, services, offers, promotions, rewards, and events offered by us and others, and provide news and information we think will be of interest to you.</li>
    <li style="list-style-type: disc;">Monitor and analyze trends, usage, and activities in connection with our Services.</li>
    <li style="list-style-type: disc;">Personalize and improve the Services and provide advertisements, content, or features that match user profiles or interests.</li>
    <li style="list-style-type: disc;">Enable user-to-user communications.</li>
    <li style="list-style-type: disc;">Enforce our terms and conditions and other usage policies.</li>
</ul> <br>

        


        <h2 style="font-size:25px">Disclosure of Your Information</h2>
        
            <li>Information may be shared with law enforcement, during business transfers, with third-party service providers, and with affiliates.</li>
       <br>
           <h2 style="font-size:25px">Third-Party Service Providers</h2>
        <li>We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and marketing assistance.
</li>
 <br>
        <h2 style="font-size:25px">Security of Your Information</h2>
        <li>We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.</li>
 <br>
        <h2 style="font-size:25px">Affiliates</h2>
        <li>We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
 <br>
        <h2 style="font-size:25px">Your Rights and Choices</h2>
        <li>You may at any time review or change the information in your account or terminate your account by:</li>
        <ul>
            <li  style="    list-style-type: disc">Logging into your account settings and updating your account</li>
            <li style=" list-style-type: disc">Contacting us using the contact information provided below</li>
        </ul>
        
         <li>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, some information may be retained in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use, and/or comply with legal requirements.</li>
 <br>
        <h2 style="font-size:25px">Policy for Children</h2>
        <li>We do not knowingly solicit information from or market to children under the age of 18. If we learn we have collected personal information from a child under age 18 without verification of parental consent, we will delete that information as quickly as possible. If you become aware of any data we have collected from children under age 18, please contact us using the contact information provided below.</li>
 <br>
        <h2 style="font-size:25px">Changes to This Privacy Policy</h2>
        <!--<h2>Use of Your Information</h2>-->
        <li>We may update this Privacy Policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal, or regulatory reasons.</li>
  <br>

        <h2 style="font-size:25px">Contact Us</h2>
        <li>For any questions regarding this privacy policy, please contact us at:</li>
        <ul>
            <li style=" list-style-type: disc">Email: <a href="mailto:shubhweds11@gmail.com">shubhweds11@gmail.com</a></li>
            <li style=" list-style-type: disc">Phone: +91 7014378070</li>
        </ul>
    </div>
    </div>

